2025-04-14 14:17:24,756 INFO    MainThread:8366 [wandb_setup.py:_flush():76] Current SDK version is 0.15.12
2025-04-14 14:17:24,757 INFO    MainThread:8366 [wandb_setup.py:_flush():76] Configure stats pid to 8366
2025-04-14 14:17:24,757 INFO    MainThread:8366 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2025-04-14 14:17:24,757 INFO    MainThread:8366 [wandb_setup.py:_flush():76] Loading settings from /root/ltu-main/ltu-main/src/ltu_as/train_scripts/wandb/settings
2025-04-14 14:17:24,757 WARNING MainThread:8366 [wandb_setup.py:_flush():76] Unknown environment variable: WANDB_WATCH
2025-04-14 14:17:24,757 WARNING MainThread:8366 [wandb_setup.py:_flush():76] Unknown environment variable: WANDB_LOG_MODEL
2025-04-14 14:17:24,757 INFO    MainThread:8366 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'ltu-as'}
2025-04-14 14:17:24,757 INFO    MainThread:8366 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2025-04-14 14:17:24,757 WARNING MainThread:8366 [wandb_setup.py:_flush():76] Could not save program above cwd: /root/ltu-main/ltu-main/src/ltu_as/train_scripts/../finetune_low_resource.py
2025-04-14 14:17:24,757 INFO    MainThread:8366 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': None, 'program_abspath': '/root/ltu-main/ltu-main/src/ltu_as/finetune_low_resource.py', 'program': '/root/ltu-main/ltu-main/src/ltu_as/train_scripts/../finetune_low_resource.py'}
2025-04-14 14:17:24,757 INFO    MainThread:8366 [wandb_init.py:_log_setup():528] Logging user logs to /root/ltu-main/ltu-main/src/ltu_as/train_scripts/wandb/run-20250414_141724-31odaggz/logs/debug.log
2025-04-14 14:17:24,758 INFO    MainThread:8366 [wandb_init.py:_log_setup():529] Logging internal logs to /root/ltu-main/ltu-main/src/ltu_as/train_scripts/wandb/run-20250414_141724-31odaggz/logs/debug-internal.log
2025-04-14 14:17:24,758 INFO    MainThread:8366 [wandb_init.py:init():568] calling init triggers
2025-04-14 14:17:24,758 INFO    MainThread:8366 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {}
2025-04-14 14:17:24,758 INFO    MainThread:8366 [wandb_init.py:init():618] starting backend
2025-04-14 14:17:24,758 INFO    MainThread:8366 [wandb_init.py:init():622] setting up manager
2025-04-14 14:17:24,760 INFO    MainThread:8366 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-04-14 14:17:24,764 INFO    MainThread:8366 [wandb_init.py:init():628] backend started and connected
2025-04-14 14:17:24,768 INFO    MainThread:8366 [wandb_init.py:init():720] updated telemetry
2025-04-14 14:17:24,769 INFO    MainThread:8366 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2025-04-14 14:17:25,564 INFO    MainThread:8366 [wandb_run.py:_on_init():2220] communicating current version
2025-04-14 14:17:25,968 INFO    MainThread:8366 [wandb_run.py:_on_init():2229] got version response upgrade_message: "wandb version 0.19.9 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2025-04-14 14:17:25,968 INFO    MainThread:8366 [wandb_init.py:init():804] starting run threads in backend
2025-04-14 14:17:41,154 WARNING MainThread:8366 [wandb_init.py:init():1192] interrupted
Traceback (most recent call last):
  File "/root/anaconda3/envs/venv_ltu/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/root/anaconda3/envs/venv_ltu/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 815, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "/root/anaconda3/envs/venv_ltu/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/root/anaconda3/envs/venv_ltu/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/root/anaconda3/envs/venv_ltu/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/root/anaconda3/envs/venv_ltu/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/root/anaconda3/envs/venv_ltu/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
